---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ollama-tls
  namespace: ollama
spec:
  secretName: ollama-tls
  privateKey:
    rotationPolicy: Always
  commonName: ollama.robinmordasiewicz.amerintlxperts.com
  dnsNames:
    - ollama.robinmordasiewicz.amerintlxperts.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
